import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Menu */}
        <header className="my-6">
          <nav className="container mx-auto">
            <ul className="flex space-x-16 font-bold">
              <li>Home</li>
              <li>Booking</li>
              <li>Contact</li>
            </ul>
          </nav>
        </header>

        {/* Everything else */}
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
